/*


 Copyright (c) 2004-2018 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_XAUI_H
#define _VTSS_DAYTONA_REG_INIT_XAUI_H

// Settings for mode SDR

#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA_SDR                              VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_SDR             VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA_SDR         VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA_SDR       VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS_SDR     VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS_SDR     VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS(0x0)


// Settings for mode DDR_A

#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA_DDR_A                            VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_DDR_A           VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA_DDR_A       VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA_DDR_A     VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS_DDR_A   VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS_DDR_A   VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS(0x0)


// Settings for mode DDR_K

#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA_DDR_K                            VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_DDR_K           VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA_DDR_K       VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA_DDR_K     VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS_DDR_K   VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS_DDR_K   VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS(0x0)


// Settings for mode DDR_M

#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA_DDR_M                            VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_DDR_M           VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA_DDR_M       VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA_DDR_M     VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS_DDR_M   VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS(0x1)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS_DDR_M   VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS(0x1)


// Settings for mode UNUSED

#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA_UNUSED                           VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_UNUSED          VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA_UNUSED      VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA_UNUSED    VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS_UNUSED  VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS(0x0)
#define  VTSS_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS_UNUSED  VTSS_F_PCS_XAUI_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS(0x0)




typedef enum {
    BM_XAUI_SDR,
    BM_XAUI_DDR_A,
    BM_XAUI_DDR_K,
    BM_XAUI_DDR_M,
    BM_XAUI_UNUSED,
    BM_XAUI_LAST
} block_xaui_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_XAUI_H */
