/*


 Copyright (c) 2002-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable format
 (e.g. HEX file) and only in or with products utilizing the Microsemi switch and
 PHY products.  The source code of the software may not be disclosed, transmitted
 or distributed without the prior written permission of Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all ownership,
 copyright, trade secret and proprietary rights in the software and its source code,
 including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL WARRANTIES
 OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES ARE EXPRESS,
 IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION, WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND NON-INFRINGEMENT.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_OTU_H
#define _VTSS_DAYTONA_REG_INIT_OTU_H

// Settings for mode OTU1_S

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU1_S                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU1_S                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU1_S                                 VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU1_S                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU1_S                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU1_S                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU1_S              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU1_S              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU1_S        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU1_S                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU1_S                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU1_S                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU1_S              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU1_S        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU1_S                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU1_S                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU1_S               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU1_S                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU1_S                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_A

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_A                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_A                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_A                                 VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_A                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_A                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_A                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_A              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_A              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_A        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_A                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_A                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_A                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_A              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_A        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_A                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_A                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_A               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_A                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_A                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_S

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_S                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_S                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_S                                 VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_S                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_S                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_S                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_S              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_S              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_S        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_S                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_S                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_S                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_S              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_S        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_S                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_S                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_S               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_S                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_S                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_GFP

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_GFP                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_GFP                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_GFP                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_GFP                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_GFP                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_GFP                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_GFP            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_GFP            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_GFP      VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_GFP              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_GFP                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_GFP                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_GFP            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_GFP      VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_GFP                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_GFP                 VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_GFP             VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_GFP                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_GFP                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_EXT

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_EXT                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_EXT                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_EXT                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x4)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_EXT                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_EXT                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_EXT                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_EXT            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_EXT            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_EXT      VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_EXT              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_EXT                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_EXT                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_EXT            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_EXT      VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_EXT                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_EXT                 VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_EXT             VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_EXT                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_EXT                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_8GFC

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_8GFC                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_8GFC                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_8GFC                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_8GFC                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_8GFC                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_8GFC                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_8GFC           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_8GFC           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_8GFC     VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_8GFC             VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_8GFC               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_8GFC                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_8GFC           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_8GFC     VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_8GFC               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_8GFC                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_8GFC            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_8GFC               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_8GFC               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU1_S_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU1_S_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU1_S_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU1_S_SFI                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x2)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU1_S_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU1_S_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU1_S_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU1_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU1_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU1_S_SFI    VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU1_S_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU1_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU1_S_SFI               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU1_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU1_S_SFI    VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU1_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU1_S_SFI               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU1_S_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU1_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU1_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_A_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_A_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_A_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_A_SFI                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x3)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_A_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_A_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_A_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_A_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_A_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_A_SFI    VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_A_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_A_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_A_SFI               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_A_SFI          VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_A_SFI    VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_A_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_A_SFI               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_A_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_A_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_A_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_S_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_S_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_S_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_S_SFI                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x3)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_S_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_S_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_S_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_S_SFI    VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_S_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_S_SFI               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_S_SFI    VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_S_SFI               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_S_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_GFP_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_GFP_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_GFP_SFI                         VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_GFP_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x2)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_GFP_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_GFP_SFI                          VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_GFP_SFI                          VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_GFP_SFI        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_GFP_SFI        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_GFP_SFI  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_GFP_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_GFP_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_GFP_SFI             VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_GFP_SFI        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_GFP_SFI  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_GFP_SFI            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_GFP_SFI             VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_GFP_SFI         VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_GFP_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_GFP_SFI            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_8GFC_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_8GFC_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_8GFC_SFI                        VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_8GFC_SFI                          VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x3)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_8GFC_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_8GFC_SFI                         VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_8GFC_SFI                         VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_8GFC_SFI       VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_8GFC_SFI       VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_8GFC_SFI VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_8GFC_SFI         VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_8GFC_SFI           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_8GFC_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_8GFC_SFI       VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_8GFC_SFI VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_8GFC_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_8GFC_SFI            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_8GFC_SFI        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_8GFC_SFI           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_8GFC_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode STREAM

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_STREAM                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_STREAM                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_STREAM                                 VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_STREAM                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_STREAM                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_STREAM                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_STREAM              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_STREAM              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_STREAM        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_STREAM                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_STREAM                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_STREAM                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_STREAM              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_STREAM        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_STREAM                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_STREAM                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_STREAM               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_STREAM                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_STREAM                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode BYP

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_BYP                                     VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_BYP                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_BYP                                    VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_BYP                                     VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_BYP                                   VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_BYP                                   VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_BYP                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_BYP                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_BYP           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_BYP                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_BYP                     VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_BYP                      VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_BYP                 VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_BYP           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_BYP                     VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_BYP                      VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_BYP                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_BYP                     VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_BYP                     VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)




typedef enum {
    BM_OTU_OTU1_S,
    BM_OTU_OTU2_A,
    BM_OTU_OTU2_S,
    BM_OTU_OTU2_GFP,
    BM_OTU_OTU2_EXT,
    BM_OTU_OTU2_8GFC,
    BM_OTU_OTU1_S_SFI,
    BM_OTU_OTU2_A_SFI,
    BM_OTU_OTU2_S_SFI,
    BM_OTU_OTU2_GFP_SFI,
    BM_OTU_OTU2_8GFC_SFI,
    BM_OTU_STREAM,
    BM_OTU_BYP,
    BM_OTU_LAST
} block_otu_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_OTU_H */
