/*


 Copyright (c) 2004-2018 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_SFI_H
#define _VTSS_DAYTONA_REG_INIT_SFI_H

// Settings for mode SDR

#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI4_ENA_SDR                                         VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI4_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI_DDR_SEL_SDR                                      VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI_DDR_SEL(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CNT_MAX_SDR                                       VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CNT_MAX(0x3f)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RESYNC_ENA_SDR                                       VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RESYNC_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SCRAM_DIS_SDR                                        VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SCRAM_DIS(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SLOOP_ENA_SDR                                        VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SLOOP_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RX_TO_TX_LOOP_ENA_SDR                                VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RX_TO_TX_LOOP_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_ENA_SDR                                           VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_POL_SDR                                           VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_POL(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_ENA_SDR                                          VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_POL_SDR                                          VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_POL(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_FAST_SYNC_ENA_SDR                                    VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_FAST_SYNC_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CL49_ENA_SDR                                      VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CL49_ENA(0x1)


// Settings for mode DDR

#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI4_ENA_DDR                                         VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI4_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI_DDR_SEL_DDR                                      VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI_DDR_SEL(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CNT_MAX_DDR                                       VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CNT_MAX(0x3f)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RESYNC_ENA_DDR                                       VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RESYNC_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SCRAM_DIS_DDR                                        VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SCRAM_DIS(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SLOOP_ENA_DDR                                        VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SLOOP_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RX_TO_TX_LOOP_ENA_DDR                                VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RX_TO_TX_LOOP_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_ENA_DDR                                           VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_POL_DDR                                           VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_POL(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_ENA_DDR                                          VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_POL_DDR                                          VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_POL(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_FAST_SYNC_ENA_DDR                                    VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_FAST_SYNC_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CL49_ENA_DDR                                      VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CL49_ENA(0x1)


// Settings for mode UNUSED

#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI4_ENA_UNUSED                                      VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI4_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI_DDR_SEL_UNUSED                                   VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SFI_DDR_SEL(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CNT_MAX_UNUSED                                    VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CNT_MAX(0x3f)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RESYNC_ENA_UNUSED                                    VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RESYNC_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SCRAM_DIS_UNUSED                                     VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SCRAM_DIS(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SLOOP_ENA_UNUSED                                     VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SLOOP_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RX_TO_TX_LOOP_ENA_UNUSED                             VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_RX_TO_TX_LOOP_ENA(0x0)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_ENA_UNUSED                                        VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_POL_UNUSED                                        VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SD_POL(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_ENA_UNUSED                                       VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_POL_UNUSED                                       VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_LOS_POL(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_FAST_SYNC_ENA_UNUSED                                 VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_FAST_SYNC_ENA(0x1)
#define  VTSS_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CL49_ENA_UNUSED                                   VTSS_F_SFI4_SFI4_CONFIGURATION_SFI4_CFG_SH_CL49_ENA(0x1)




typedef enum {
    BM_SFI_SDR,
    BM_SFI_DDR,
    BM_SFI_UNUSED,
    BM_SFI_LAST
} block_sfi_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_SFI_H */
