/*


 Copyright (c) 2002-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable format
 (e.g. HEX file) and only in or with products utilizing the Microsemi switch and
 PHY products.  The source code of the software may not be disclosed, transmitted
 or distributed without the prior written permission of Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all ownership,
 copyright, trade secret and proprietary rights in the software and its source code,
 including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL WARRANTIES
 OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES ARE EXPRESS,
 IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION, WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND NON-INFRINGEMENT.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_XFI_HSS11G_H
#define _VTSS_DAYTONA_REG_INIT_XFI_HSS11G_H

// Settings for mode OTU2

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_OTU2                                           VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_OTU2                                          VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2                           VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2                           VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_OTU2                                 VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_OTU2                                VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode OTU2_X4

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_OTU2_X4                                        VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_OTU2_X4                                       VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2_X4                        VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2_X4                        VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_X4                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_X4                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_X4                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_X4                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_OTU2_X4                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_OTU2_X4                             VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2_X4                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2_X4                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode OTU2E

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_OTU2E                                          VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_OTU2E                                         VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_OTU2E                                VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_OTU2E                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2E                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2E                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode OTU2E_X4

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_OTU2E_X4                                       VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_OTU2E_X4                                      VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E_X4                       VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E_X4                       VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_OTU2E_X4                             VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_OTU2E_X4                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2E_X4                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2E_X4                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode OTU1E

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_OTU1E                                          VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_OTU1E                                         VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_OTU1E                                VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_OTU1E                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU1E                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU1E                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode OTU1E_X4

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_OTU1E_X4                                       VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_OTU1E_X4                                      VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E_X4                       VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E_X4                       VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_OTU1E_X4                             VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_OTU1E_X4                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU1E_X4                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU1E_X4                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode OTU2F

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_OTU2F                                          VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_OTU2F                                         VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_OTU2F                                VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_OTU2F                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2F                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2F                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode OTU2F_X4

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_OTU2F_X4                                       VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_OTU2F_X4                                      VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F_X4                       VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F_X4                       VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_OTU2F_X4                             VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_OTU2F_X4                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2F_X4                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_OTU2F_X4                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode SONET

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_SONET                                          VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_SONET                                         VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_SONET                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_SONET                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_SONET                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_SONET                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_SONET                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_SONET                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_SONET                                VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_SONET                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_SONET                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_SONET                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode SONET_X4

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_SONET_X4                                       VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_SONET_X4                                      VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_SONET_X4                       VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_SONET_X4                       VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_SONET_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_SONET_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_SONET_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_SONET_X4                       VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_SONET_X4                             VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_SONET_X4                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_SONET_X4                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_SONET_X4                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode 10GELAN

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_10GELAN                                        VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_10GELAN                                       VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_10GELAN                        VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_10GELAN                        VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_10GELAN                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_10GELAN                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_10GELAN                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_10GELAN                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_10GELAN                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_10GELAN                             VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_10GELAN                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_10GELAN                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode 10GEWAN

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_10GEWAN                                        VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_10GEWAN                                       VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_10GEWAN                        VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_10GEWAN                        VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_10GEWAN                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_10GEWAN                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_10GEWAN                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_10GEWAN                        VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_10GEWAN                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_10GEWAN                             VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_10GEWAN                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_10GEWAN                            VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode 10GFC

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_10GFC                                          VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_10GFC                                         VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_10GFC                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_10GFC                          VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_10GFC                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_10GFC                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_10GFC                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_10GFC                          VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_10GFC                                VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_10GFC                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x1)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_10GFC                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_10GFC                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode 8GFC

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_8GFC                                           VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_8GFC                                          VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x0)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_8GFC                           VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_8GFC                           VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_8GFC                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_8GFC                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_8GFC                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_8GFC                           VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_8GFC                                 VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_8GFC                                VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_8GFC                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_8GFC                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x8)


// Settings for mode UNUSED

#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL_UNUSED                                         VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSDIVSEL(0x0)
#define  VTSS_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL_UNUSED                                        VTSS_F_XFI_XFI_CONTROL_HSS_CONTROLS_HSSPDWNPLL(0x1)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL_UNUSED                         VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL_UNUSED                         VTSS_F_XFI_HSS11G_TX_HSS11G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_UNUSED                         VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_UNUSED                         VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL_UNUSED                         VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL_UNUSED                         VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE_UNUSED                               VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RRATE(0x2)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN_UNUSED                              VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_TEST_CONTROL_RCLKEN(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_UNUSED                             VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x0)
#define  VTSS_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL_UNUSED                             VTSS_F_XFI_HSS11G_RX_HSS11G_RECEIVER_SIGDET_CONTROL_SDLVL(0x0)




typedef enum {
    BM_XFI_HSS11G_OTU2,
    BM_XFI_HSS11G_OTU2_X4,
    BM_XFI_HSS11G_OTU2E,
    BM_XFI_HSS11G_OTU2E_X4,
    BM_XFI_HSS11G_OTU1E,
    BM_XFI_HSS11G_OTU1E_X4,
    BM_XFI_HSS11G_OTU2F,
    BM_XFI_HSS11G_OTU2F_X4,
    BM_XFI_HSS11G_SONET,
    BM_XFI_HSS11G_SONET_X4,
    BM_XFI_HSS11G_10GELAN,
    BM_XFI_HSS11G_10GEWAN,
    BM_XFI_HSS11G_10GFC,
    BM_XFI_HSS11G_8GFC,
    BM_XFI_HSS11G_UNUSED,
    BM_XFI_HSS11G_LAST
} block_xfi_hss11g_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_XFI_HSS11G_H */
