/*


 Copyright (c) 2004-2018 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_OTU_H
#define _VTSS_DAYTONA_REG_INIT_OTU_H

// Settings for mode OTU1_S

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU1_S                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU1_S                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU1_S                                 VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU1_S                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU1_S                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU1_S                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU1_S              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU1_S              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU1_S        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU1_S                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU1_S                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU1_S                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU1_S              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU1_S        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU1_S                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU1_S                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU1_S               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU1_S                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU1_S                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_A

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_A                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_A                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_A                                 VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_A                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_A                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_A                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_A              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_A              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_A        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_A                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_A                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_A                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_A              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_A        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_A                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_A                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_A               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_A                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_A                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_S

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_S                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_S                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_S                                 VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_S                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_S                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_S                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_S              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_S              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_S        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_S                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_S                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_S                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_S              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_S        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_S                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_S                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_S               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_S                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_S                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_GFP

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_GFP                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_GFP                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_GFP                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_GFP                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_GFP                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_GFP                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_GFP            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_GFP            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_GFP      VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_GFP              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_GFP                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_GFP                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_GFP            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_GFP      VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_GFP                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_GFP                 VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_GFP             VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_GFP                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_GFP                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_EXT

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_EXT                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_EXT                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_EXT                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x4)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_EXT                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_EXT                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_EXT                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_EXT            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_EXT            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_EXT      VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_EXT              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_EXT                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_EXT                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_EXT            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_EXT      VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_EXT                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_EXT                 VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_EXT             VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_EXT                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_EXT                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_8GFC

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_8GFC                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_8GFC                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_8GFC                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_8GFC                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_8GFC                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_8GFC                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_8GFC           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_8GFC           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_8GFC     VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_8GFC             VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_8GFC               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_8GFC                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_8GFC           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_8GFC     VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_8GFC               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_8GFC                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_8GFC            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_8GFC               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_8GFC               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU1_S_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU1_S_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU1_S_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU1_S_SFI                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x2)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU1_S_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU1_S_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU1_S_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU1_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU1_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU1_S_SFI    VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU1_S_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU1_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU1_S_SFI               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU1_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU1_S_SFI    VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU1_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU1_S_SFI               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU1_S_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU1_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU1_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_A_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_A_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_A_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_A_SFI                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x3)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_A_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_A_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_A_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_A_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_A_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_A_SFI    VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_A_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_A_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_A_SFI               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_A_SFI          VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_A_SFI    VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_A_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_A_SFI               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_A_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_A_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_A_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_S_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_S_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_S_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_S_SFI                             VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x3)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_S_SFI                              VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_S_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_S_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_S_SFI    VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_S_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_S_SFI               VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_S_SFI          VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_S_SFI    VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_S_SFI               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_S_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_S_SFI              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_GFP_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_GFP_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_GFP_SFI                         VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_GFP_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x2)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_GFP_SFI                            VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_GFP_SFI                          VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_GFP_SFI                          VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_GFP_SFI        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_GFP_SFI        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_GFP_SFI  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_GFP_SFI          VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_GFP_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_GFP_SFI             VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_GFP_SFI        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_GFP_SFI  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_GFP_SFI            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_GFP_SFI             VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_GFP_SFI         VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_GFP_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_GFP_SFI            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode OTU2_8GFC_SFI

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_OTU2_8GFC_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_OTU2_8GFC_SFI                        VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_OTU2_8GFC_SFI                          VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x3)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_OTU2_8GFC_SFI                           VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_OTU2_8GFC_SFI                         VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_OTU2_8GFC_SFI                         VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_8GFC_SFI       VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_OTU2_8GFC_SFI       VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_8GFC_SFI VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_OTU2_8GFC_SFI         VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_8GFC_SFI           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_8GFC_SFI            VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_OTU2_8GFC_SFI       VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_OTU2_8GFC_SFI VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_OTU2_8GFC_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_OTU2_8GFC_SFI            VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_OTU2_8GFC_SFI        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_8GFC_SFI           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_OTU2_8GFC_SFI           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode STREAM

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_STREAM                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_STREAM                               VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_STREAM                                 VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_STREAM                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_STREAM                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_STREAM                                VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_STREAM              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_STREAM              VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_STREAM        VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_STREAM                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_STREAM                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_STREAM                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_STREAM              VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_STREAM        VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_STREAM                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_STREAM                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_STREAM               VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_STREAM                  VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_STREAM                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)


// Settings for mode BYP

#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL_BYP                                     VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GFP_SEL(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN_BYP                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_OTU2ODU_EN(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE_BYP                                    VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_GAP_MODE(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA_BYP                                     VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_CLK_ENA(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS_BYP                                   VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_TX_BYPASS(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS_BYP                                   VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_RX_BYPASS(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE_BYP                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE_BYP                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_OTU_FRAME_TYPE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_BYP           VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING_BYP                   VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_FA_OTU_CONTROL_OTU_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING_BYP                     VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE_BYP                      VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE_BYP                 VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_STREAMING_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD_BYP           VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTENDED_OPU_PAYLOAD(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING_BYP                     VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_ASYNC_MAPPING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE_BYP                      VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_OPU_CONTROL_STUFF_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE_BYP                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_ERR_SYNC_MODE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET_BYP                     VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET_BYP                     VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FIFO_RESET(0x1)




typedef enum {
    BM_OTU_OTU1_S,
    BM_OTU_OTU2_A,
    BM_OTU_OTU2_S,
    BM_OTU_OTU2_GFP,
    BM_OTU_OTU2_EXT,
    BM_OTU_OTU2_8GFC,
    BM_OTU_OTU1_S_SFI,
    BM_OTU_OTU2_A_SFI,
    BM_OTU_OTU2_S_SFI,
    BM_OTU_OTU2_GFP_SFI,
    BM_OTU_OTU2_8GFC_SFI,
    BM_OTU_STREAM,
    BM_OTU_BYP,
    BM_OTU_LAST
} block_otu_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_OTU_H */
