/*


 Copyright (c) 2004-2018 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_OTU_FEC_H
#define _VTSS_DAYTONA_REG_INIT_OTU_FEC_H

// Settings for mode EFECI7

#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING_EFECI7                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_EFECI7                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE_EFECI7                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_EFECI7                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL_EFECI7                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL(0x1)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY_EFECI7           VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS_EFECI7         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN_EFECI7         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS_EFECI7     VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN_EFECI7          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA_EFECI7            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST_EFECI7            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS_EFECI7            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA_EFECI7            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA(0x0)


// Settings for mode EFECI4

#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING_EFECI4                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_EFECI4                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE_EFECI4                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_EFECI4                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL_EFECI4                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY_EFECI4           VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY(0x3)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS_EFECI4         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN_EFECI4         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS_EFECI4     VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN_EFECI4          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN(0x1)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA_EFECI4            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA(0x1)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST_EFECI4            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS_EFECI4            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA_EFECI4            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA(0x1)


// Settings for mode RSFEC

#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING_RSFEC                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_RSFEC                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE_RSFEC                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_RSFEC                 VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL_RSFEC                                   VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY_RSFEC            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS_RSFEC          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN_RSFEC          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS_RSFEC      VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN_RSFEC           VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA_RSFEC             VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST_RSFEC             VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS_RSFEC             VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS(0x1)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA_RSFEC             VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA(0x0)


// Settings for mode UNUSED

#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING_UNUSED                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_UNUSED                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE_UNUSED                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_UNUSED                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL_UNUSED                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY_UNUSED           VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS_UNUSED         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN_UNUSED         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS_UNUSED     VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN_UNUSED          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA_UNUSED            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST_UNUSED            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS_UNUSED            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS(0x1)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA_UNUSED            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA(0x0)




typedef enum {
    BM_OTU_FEC_EFECI7,
    BM_OTU_FEC_EFECI4,
    BM_OTU_FEC_RSFEC,
    BM_OTU_FEC_UNUSED,
    BM_OTU_FEC_LAST
} block_otu_fec_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_OTU_FEC_H */
