/*


 Copyright (c) 2004-2018 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_UPI_H
#define _VTSS_DAYTONA_REG_INIT_UPI_H

// Settings for mode XAUI_10GE_SDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_XAUI_10GE_SDR                                  VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_XAUI_10GE_SDR                                VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_XAUI_10GE_SDR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_XAUI_10GE_SDR                                  VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_XAUI_10GE_SDR                                VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_XAUI_10GE_SDR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_XAUI_10GE_SDR                        VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode XAUI_10GE_DDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_XAUI_10GE_DDR                                  VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_XAUI_10GE_DDR                                VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_XAUI_10GE_DDR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_XAUI_10GE_DDR                                  VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_XAUI_10GE_DDR                                VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_XAUI_10GE_DDR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_XAUI_10GE_DDR                        VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode XAUI_10GFC_SDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_XAUI_10GFC_SDR                                 VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_XAUI_10GFC_SDR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_XAUI_10GFC_SDR                              VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_XAUI_10GFC_SDR                                 VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_XAUI_10GFC_SDR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_XAUI_10GFC_SDR                              VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_XAUI_10GFC_SDR                       VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode XAUI_10GFC_DDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_XAUI_10GFC_DDR                                 VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_XAUI_10GFC_DDR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_XAUI_10GFC_DDR                              VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_XAUI_10GFC_DDR                                 VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_XAUI_10GFC_DDR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_XAUI_10GFC_DDR                              VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_XAUI_10GFC_DDR                       VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode TFI5_SDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_TFI5_SDR                                       VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_TFI5_SDR                                     VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_TFI5_SDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x2)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_TFI5_SDR                                       VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_TFI5_SDR                                     VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_TFI5_SDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x2)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_TFI5_SDR                             VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode TFI5_DDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_TFI5_DDR                                       VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_TFI5_DDR                                     VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_TFI5_DDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x2)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_TFI5_DDR                                       VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_TFI5_DDR                                     VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_TFI5_DDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x2)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_TFI5_DDR                             VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode SFI42_SDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_SFI42_SDR                                      VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_SFI42_SDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_SFI42_SDR                                   VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_SFI42_SDR                                      VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_SFI42_SDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_SFI42_SDR                                   VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_SFI42_SDR                            VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode SFI42_DDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_SFI42_DDR                                      VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_SFI42_DDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_SFI42_DDR                                   VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_SFI42_DDR                                      VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_SFI42_DDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_SFI42_DDR                                   VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_SFI42_DDR                            VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode SFI42_SDR_FRMR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_SFI42_SDR_FRMR                                 VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_SFI42_SDR_FRMR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_SFI42_SDR_FRMR                              VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_SFI42_SDR_FRMR                                 VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_SFI42_SDR_FRMR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_SFI42_SDR_FRMR                              VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_SFI42_SDR_FRMR                       VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x1)


// Settings for mode SFI42_DDR_FRMR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_SFI42_DDR_FRMR                                 VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_SFI42_DDR_FRMR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_SFI42_DDR_FRMR                              VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_SFI42_DDR_FRMR                                 VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_SFI42_DDR_FRMR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_SFI42_DDR_FRMR                              VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_SFI42_DDR_FRMR                       VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x1)


// Settings for mode UNUSED

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_UNUSED                                         VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_UNUSED                                       VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_UNUSED                                      VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_UNUSED                                         VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_UNUSED                                       VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_UNUSED                                      VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_UNUSED                               VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)




typedef enum {
    BM_UPI_XAUI_10GE_SDR,
    BM_UPI_XAUI_10GE_DDR,
    BM_UPI_XAUI_10GFC_SDR,
    BM_UPI_XAUI_10GFC_DDR,
    BM_UPI_TFI5_SDR,
    BM_UPI_TFI5_DDR,
    BM_UPI_SFI42_SDR,
    BM_UPI_SFI42_DDR,
    BM_UPI_SFI42_SDR_FRMR,
    BM_UPI_SFI42_DDR_FRMR,
    BM_UPI_UNUSED,
    BM_UPI_LAST
} block_upi_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_UPI_H */
