/*


 Copyright (c) 2002-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable format
 (e.g. HEX file) and only in or with products utilizing the Microsemi switch and
 PHY products.  The source code of the software may not be disclosed, transmitted
 or distributed without the prior written permission of Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all ownership,
 copyright, trade secret and proprietary rights in the software and its source code,
 including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL WARRANTIES
 OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES ARE EXPRESS,
 IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION, WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND NON-INFRINGEMENT.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_UPI_H
#define _VTSS_DAYTONA_REG_INIT_UPI_H

// Settings for mode XAUI_10GE_SDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_XAUI_10GE_SDR                                  VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_XAUI_10GE_SDR                                VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_XAUI_10GE_SDR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_XAUI_10GE_SDR                                  VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_XAUI_10GE_SDR                                VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_XAUI_10GE_SDR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_XAUI_10GE_SDR                        VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode XAUI_10GE_DDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_XAUI_10GE_DDR                                  VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_XAUI_10GE_DDR                                VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_XAUI_10GE_DDR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_XAUI_10GE_DDR                                  VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_XAUI_10GE_DDR                                VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_XAUI_10GE_DDR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_XAUI_10GE_DDR                        VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode XAUI_10GFC_SDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_XAUI_10GFC_SDR                                 VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_XAUI_10GFC_SDR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_XAUI_10GFC_SDR                              VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_XAUI_10GFC_SDR                                 VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_XAUI_10GFC_SDR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_XAUI_10GFC_SDR                              VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_XAUI_10GFC_SDR                       VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode XAUI_10GFC_DDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_XAUI_10GFC_DDR                                 VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_XAUI_10GFC_DDR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_XAUI_10GFC_DDR                              VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_XAUI_10GFC_DDR                                 VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_XAUI_10GFC_DDR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_XAUI_10GFC_DDR                              VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_XAUI_10GFC_DDR                       VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode TFI5_SDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_TFI5_SDR                                       VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_TFI5_SDR                                     VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_TFI5_SDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x2)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_TFI5_SDR                                       VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_TFI5_SDR                                     VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_TFI5_SDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x2)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_TFI5_SDR                             VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode TFI5_DDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_TFI5_DDR                                       VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_TFI5_DDR                                     VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_TFI5_DDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x2)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_TFI5_DDR                                       VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x3)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_TFI5_DDR                                     VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_TFI5_DDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x2)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_TFI5_DDR                             VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode SFI42_SDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_SFI42_SDR                                      VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_SFI42_SDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_SFI42_SDR                                   VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_SFI42_SDR                                      VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_SFI42_SDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_SFI42_SDR                                   VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_SFI42_SDR                            VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode SFI42_DDR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_SFI42_DDR                                      VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_SFI42_DDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_SFI42_DDR                                   VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_SFI42_DDR                                      VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_SFI42_DDR                                    VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_SFI42_DDR                                   VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_SFI42_DDR                            VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)


// Settings for mode SFI42_SDR_FRMR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_SFI42_SDR_FRMR                                 VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_SFI42_SDR_FRMR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_SFI42_SDR_FRMR                              VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_SFI42_SDR_FRMR                                 VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_SFI42_SDR_FRMR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_SFI42_SDR_FRMR                              VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_SFI42_SDR_FRMR                       VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x1)


// Settings for mode SFI42_DDR_FRMR

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_SFI42_DDR_FRMR                                 VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_SFI42_DDR_FRMR                               VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_SFI42_DDR_FRMR                              VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_SFI42_DDR_FRMR                                 VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_SFI42_DDR_FRMR                               VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x1)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_SFI42_DDR_FRMR                              VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x1)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_SFI42_DDR_FRMR                       VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x1)


// Settings for mode UNUSED

#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN_UNUSED                                         VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE_UNUSED                                       VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL_UNUSED                                      VTSS_F_UPI_UPI_CONFIG_UPI_RX_CONFIG_RX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN_UNUSED                                         VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_ENDIAN(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE_UNUSED                                       VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_DDR_MODE(0x0)
#define  VTSS_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL_UNUSED                                      VTSS_F_UPI_UPI_CONFIG_UPI_TX_CONFIG_TX_PROTO_SEL(0x0)
#define  VTSS_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA_UNUSED                               VTSS_F_UPI_UPI_RX_OTN_FRMR_UPI_RX_OTN_FRMR_ENA_FRMR_ENA(0x0)




typedef enum {
    BM_UPI_XAUI_10GE_SDR,
    BM_UPI_XAUI_10GE_DDR,
    BM_UPI_XAUI_10GFC_SDR,
    BM_UPI_XAUI_10GFC_DDR,
    BM_UPI_TFI5_SDR,
    BM_UPI_TFI5_DDR,
    BM_UPI_SFI42_SDR,
    BM_UPI_SFI42_DDR,
    BM_UPI_SFI42_SDR_FRMR,
    BM_UPI_SFI42_DDR_FRMR,
    BM_UPI_UNUSED,
    BM_UPI_LAST
} block_upi_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_UPI_H */
