/*


 Copyright (c) 2002-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable format
 (e.g. HEX file) and only in or with products utilizing the Microsemi switch and
 PHY products.  The source code of the software may not be disclosed, transmitted
 or distributed without the prior written permission of Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all ownership,
 copyright, trade secret and proprietary rights in the software and its source code,
 including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL WARRANTIES
 OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES ARE EXPRESS,
 IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION, WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND NON-INFRINGEMENT.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_MAC_H
#define _VTSS_DAYTONA_REG_INIT_MAC_H

// Settings for mode INTR_MON

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_INTR_MON                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_INTR_MON                       VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_INTR_MON                                     VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_INTR_MON                                     VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_INTR_MON                           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_INTR_MON                                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_INTR_MON                           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_INTR_MON                                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_INTR_MON                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_INTR_MON                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_INTR_MON                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_INTR_MON                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_INTR_MON                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_INTR_MON                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_INTR_MON                              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_INTR_MON                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_INTR_MON                                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_INTR_MON                            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_INTR_MON                            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_INTR_MON                  VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_INTR_MON                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_INTR_MON                              VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_INTR_MON               VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_INTR_MON               VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_INTR_MON                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_INTR_MON                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_INTR_MON              VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_INTR_MON         VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode INTR_MON_PACE_EN

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_INTR_MON_PACE_EN                     VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_INTR_MON_PACE_EN               VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_INTR_MON_PACE_EN                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_INTR_MON_PACE_EN                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_INTR_MON_PACE_EN                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_INTR_MON_PACE_EN                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_INTR_MON_PACE_EN                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_INTR_MON_PACE_EN                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_INTR_MON_PACE_EN                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_INTR_MON_PACE_EN                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_INTR_MON_PACE_EN                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_INTR_MON_PACE_EN                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_INTR_MON_PACE_EN           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_INTR_MON_PACE_EN                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_INTR_MON_PACE_EN                      VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_INTR_MON_PACE_EN             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_INTR_MON_PACE_EN                         VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_INTR_MON_PACE_EN                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_INTR_MON_PACE_EN                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_INTR_MON_PACE_EN          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_INTR_MON_PACE_EN            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_INTR_MON_PACE_EN                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_INTR_MON_PACE_EN       VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_INTR_MON_PACE_EN       VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_INTR_MON_PACE_EN                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_INTR_MON_PACE_EN                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_INTR_MON_PACE_EN      VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_INTR_MON_PACE_EN VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode INTR_MON_FC_EN

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_INTR_MON_FC_EN                       VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_INTR_MON_FC_EN                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_INTR_MON_FC_EN                               VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_INTR_MON_FC_EN                               VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_INTR_MON_FC_EN                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_INTR_MON_FC_EN                          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_INTR_MON_FC_EN                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_INTR_MON_FC_EN                          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_INTR_MON_FC_EN                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_INTR_MON_FC_EN                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_INTR_MON_FC_EN                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_INTR_MON_FC_EN                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_INTR_MON_FC_EN             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_INTR_MON_FC_EN                  VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_INTR_MON_FC_EN                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_INTR_MON_FC_EN               VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_INTR_MON_FC_EN                           VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_INTR_MON_FC_EN                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_INTR_MON_FC_EN                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_INTR_MON_FC_EN            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_INTR_MON_FC_EN              VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_INTR_MON_FC_EN                        VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_INTR_MON_FC_EN         VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x2)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_INTR_MON_FC_EN         VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_INTR_MON_FC_EN                  VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_INTR_MON_FC_EN                  VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_INTR_MON_FC_EN        VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0xffff)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_INTR_MON_FC_EN   VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0xa)


// Settings for mode PASS_MON

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_PASS_MON                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_PASS_MON                       VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_PASS_MON                                     VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_PASS_MON                                     VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_PASS_MON                           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_PASS_MON                                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_PASS_MON                           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_PASS_MON                                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_PASS_MON                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_PASS_MON                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_PASS_MON                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_PASS_MON                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_PASS_MON                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_PASS_MON                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_PASS_MON                              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_PASS_MON                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_PASS_MON                                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_PASS_MON                            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_PASS_MON                            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_PASS_MON                  VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_PASS_MON                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_PASS_MON                              VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_PASS_MON               VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_PASS_MON               VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_PASS_MON                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_PASS_MON                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_PASS_MON              VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_PASS_MON         VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode PASS_MON_XAUI

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_PASS_MON_XAUI                        VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_PASS_MON_XAUI                  VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_PASS_MON_XAUI                                VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_PASS_MON_XAUI                                VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_PASS_MON_XAUI                      VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_PASS_MON_XAUI                           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_PASS_MON_XAUI                      VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_PASS_MON_XAUI                           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_PASS_MON_XAUI                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_PASS_MON_XAUI                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_PASS_MON_XAUI                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_PASS_MON_XAUI                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_PASS_MON_XAUI              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_PASS_MON_XAUI                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_PASS_MON_XAUI                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_PASS_MON_XAUI                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_PASS_MON_XAUI                            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x27d8)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_PASS_MON_XAUI                       VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_PASS_MON_XAUI                       VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_PASS_MON_XAUI             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_PASS_MON_XAUI               VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_PASS_MON_XAUI                         VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_PASS_MON_XAUI          VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_PASS_MON_XAUI          VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_PASS_MON_XAUI                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_PASS_MON_XAUI                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_PASS_MON_XAUI         VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_PASS_MON_XAUI    VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode PASS_MON_PCS

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_PASS_MON_PCS                         VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_PASS_MON_PCS                   VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_PASS_MON_PCS                                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_PASS_MON_PCS                                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_PASS_MON_PCS                       VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_PASS_MON_PCS                            VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_PASS_MON_PCS                       VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_PASS_MON_PCS                            VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_PASS_MON_PCS                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_PASS_MON_PCS                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_PASS_MON_PCS                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_PASS_MON_PCS                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_PASS_MON_PCS               VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_PASS_MON_PCS                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_PASS_MON_PCS                          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_PASS_MON_PCS                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_PASS_MON_PCS                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x27d8)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_PASS_MON_PCS                        VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_PASS_MON_PCS                        VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_PASS_MON_PCS              VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_PASS_MON_PCS                VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_PASS_MON_PCS                          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_PASS_MON_PCS           VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_PASS_MON_PCS           VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_PASS_MON_PCS                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_PASS_MON_PCS                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_PASS_MON_PCS          VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_PASS_MON_PCS     VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode PASS_MON_PCS_BYP

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_PASS_MON_PCS_BYP                     VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_PASS_MON_PCS_BYP               VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_PASS_MON_PCS_BYP                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_PASS_MON_PCS_BYP                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_PASS_MON_PCS_BYP                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_PASS_MON_PCS_BYP                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_PASS_MON_PCS_BYP                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_PASS_MON_PCS_BYP                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_PASS_MON_PCS_BYP                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_PASS_MON_PCS_BYP                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_PASS_MON_PCS_BYP                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_PASS_MON_PCS_BYP                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_PASS_MON_PCS_BYP           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_PASS_MON_PCS_BYP                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_PASS_MON_PCS_BYP                      VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_PASS_MON_PCS_BYP             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_PASS_MON_PCS_BYP                         VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_PASS_MON_PCS_BYP                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_PASS_MON_PCS_BYP                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_PASS_MON_PCS_BYP          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_PASS_MON_PCS_BYP            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_PASS_MON_PCS_BYP                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_PASS_MON_PCS_BYP       VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_PASS_MON_PCS_BYP       VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_PASS_MON_PCS_BYP                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_PASS_MON_PCS_BYP                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_PASS_MON_PCS_BYP      VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_PASS_MON_PCS_BYP VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode PASS_MON_GFP

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_PASS_MON_GFP                         VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_PASS_MON_GFP                   VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_PASS_MON_GFP                                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_PASS_MON_GFP                                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_PASS_MON_GFP                       VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_PASS_MON_GFP                            VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_PASS_MON_GFP                       VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_PASS_MON_GFP                            VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_PASS_MON_GFP                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_PASS_MON_GFP                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x2)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_PASS_MON_GFP                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_PASS_MON_GFP                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_PASS_MON_GFP               VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_PASS_MON_GFP                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_PASS_MON_GFP                          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_PASS_MON_GFP                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_PASS_MON_GFP                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_PASS_MON_GFP                        VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_PASS_MON_GFP                        VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_PASS_MON_GFP              VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_PASS_MON_GFP                VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_PASS_MON_GFP                          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_PASS_MON_GFP           VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_PASS_MON_GFP           VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_PASS_MON_GFP                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_PASS_MON_GFP                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_PASS_MON_GFP          VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_PASS_MON_GFP     VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode BYP

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_BYP                                  VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_BYP                            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_BYP                                          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_BYP                                          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_BYP                                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_BYP                                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_BYP                                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_BYP                                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_BYP                              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_BYP                              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_BYP                              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_BYP                              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_BYP                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_BYP                             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_BYP                                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_BYP                          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_BYP                                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_BYP                                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_BYP                                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_BYP                       VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_BYP                         VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_BYP                                   VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_BYP                    VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_BYP                    VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_BYP                             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_BYP                             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_BYP                   VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_BYP              VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode BYP_PCS

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_BYP_PCS                              VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_BYP_PCS                        VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_BYP_PCS                                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_BYP_PCS                                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_BYP_PCS                            VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_BYP_PCS                                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_BYP_PCS                            VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_BYP_PCS                                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_BYP_PCS                          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_BYP_PCS                          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_BYP_PCS                          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_BYP_PCS                          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_BYP_PCS                    VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_BYP_PCS                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_BYP_PCS                               VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_BYP_PCS                      VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_BYP_PCS                                  VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_BYP_PCS                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_BYP_PCS                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_BYP_PCS                   VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_BYP_PCS                     VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_BYP_PCS                               VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_BYP_PCS                VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_BYP_PCS                VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_BYP_PCS                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_BYP_PCS                         VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_BYP_PCS               VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_BYP_PCS          VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode XAUI_PCS_SEL_ACTIVE

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_XAUI_PCS_SEL_ACTIVE                  VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_XAUI_PCS_SEL_ACTIVE            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_XAUI_PCS_SEL_ACTIVE                          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_XAUI_PCS_SEL_ACTIVE                          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_XAUI_PCS_SEL_ACTIVE                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_XAUI_PCS_SEL_ACTIVE                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_XAUI_PCS_SEL_ACTIVE                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_XAUI_PCS_SEL_ACTIVE                     VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_XAUI_PCS_SEL_ACTIVE              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_XAUI_PCS_SEL_ACTIVE              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_XAUI_PCS_SEL_ACTIVE              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_XAUI_PCS_SEL_ACTIVE              VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_XAUI_PCS_SEL_ACTIVE        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_XAUI_PCS_SEL_ACTIVE             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_XAUI_PCS_SEL_ACTIVE                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_XAUI_PCS_SEL_ACTIVE          VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_XAUI_PCS_SEL_ACTIVE                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_XAUI_PCS_SEL_ACTIVE                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_XAUI_PCS_SEL_ACTIVE                 VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_XAUI_PCS_SEL_ACTIVE       VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_XAUI_PCS_SEL_ACTIVE         VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_XAUI_PCS_SEL_ACTIVE                   VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_XAUI_PCS_SEL_ACTIVE    VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_XAUI_PCS_SEL_ACTIVE    VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_XAUI_PCS_SEL_ACTIVE             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_XAUI_PCS_SEL_ACTIVE             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_XAUI_PCS_SEL_ACTIVE   VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_XAUI_PCS_SEL_ACTIVE VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode XAUI_PCS_PACE_EN

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_XAUI_PCS_PACE_EN                     VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_XAUI_PCS_PACE_EN               VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_XAUI_PCS_PACE_EN                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_XAUI_PCS_PACE_EN                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_XAUI_PCS_PACE_EN                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_XAUI_PCS_PACE_EN                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_XAUI_PCS_PACE_EN                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_XAUI_PCS_PACE_EN                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_XAUI_PCS_PACE_EN                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_XAUI_PCS_PACE_EN                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_XAUI_PCS_PACE_EN                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_XAUI_PCS_PACE_EN                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_XAUI_PCS_PACE_EN           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_XAUI_PCS_PACE_EN                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_XAUI_PCS_PACE_EN                      VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_XAUI_PCS_PACE_EN             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_XAUI_PCS_PACE_EN                         VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_XAUI_PCS_PACE_EN                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_XAUI_PCS_PACE_EN                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_XAUI_PCS_PACE_EN          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_XAUI_PCS_PACE_EN            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_XAUI_PCS_PACE_EN                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_XAUI_PCS_PACE_EN       VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_XAUI_PCS_PACE_EN       VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_XAUI_PCS_PACE_EN                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_XAUI_PCS_PACE_EN                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_XAUI_PCS_PACE_EN      VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_XAUI_PCS_PACE_EN VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)


// Settings for mode XAUI_PCS_GENERIC

#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA_XAUI_PCS_GENERIC                     VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_PACE_MODE_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS_XAUI_PCS_GENERIC               VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MODE_CFG_ALLOW_SHORT_PACKETS(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA_XAUI_PCS_GENERIC                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA_XAUI_PCS_GENERIC                             VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN_XAUI_PCS_GENERIC                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST_XAUI_PCS_GENERIC                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN_XAUI_PCS_GENERIC                   VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_CLOCK_EN(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST_XAUI_PCS_GENERIC                        VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_RST(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL_XAUI_PCS_GENERIC                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_TX_SOURCE_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL_XAUI_PCS_GENERIC                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_RX_SOURCE_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL_XAUI_PCS_GENERIC                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_TX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL_XAUI_PCS_GENERIC                 VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL_XAUI_PCS_GENERIC           VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_PMA_XGMII_RX_BYPASS_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL_XAUI_PCS_GENERIC                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_MAC_PMA_RX_CLK_SEL(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL_XAUI_PCS_GENERIC                      VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_XAUI_PCS_SEL(0x1)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE_XAUI_PCS_GENERIC             VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_RST_CTRL_IGNORE_PCS_SYNC_STATE(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_XAUI_PCS_GENERIC                         VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(0x2800)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA_XAUI_PCS_GENERIC                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA_XAUI_PCS_GENERIC                    VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA(0x0)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS_XAUI_PCS_GENERIC          VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_DISCARD_DIS(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS_XAUI_PCS_GENERIC            VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_FCS_ERROR_COUNT_DIS(0x1)
#define  VTSS_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA_XAUI_PCS_GENERIC                      VTSS_F_MAC10G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE_XAUI_PCS_GENERIC       VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE_XAUI_PCS_GENERIC       VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_RX_FRAME_CONTROL_MAC_RX_PAUSE_MODE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB_XAUI_PCS_GENERIC                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_MSB_MAC_ADDRESS_MSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB_XAUI_PCS_GENERIC                VTSS_F_MAC10G_DEV_CFG_STATUS_MAC_ADDRESS_LSB_MAC_ADDRESS_LSB(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE_XAUI_PCS_GENERIC      VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_MAC_TX_PAUSE_VALUE(0x0)
#define  VTSS_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL_XAUI_PCS_GENERIC VTSS_F_MAC10G_DEV_CFG_STATUS_PAUSE_TX_FRAME_CONTROL_2_MAC_TX_PAUSE_INTERVAL(0x0)




typedef enum {
    BM_MAC_INTR_MON,
    BM_MAC_INTR_MON_PACE_EN,
    BM_MAC_INTR_MON_FC_EN,
    BM_MAC_PASS_MON,
    BM_MAC_PASS_MON_XAUI,
    BM_MAC_PASS_MON_PCS,
    BM_MAC_PASS_MON_PCS_BYP,
    BM_MAC_PASS_MON_GFP,
    BM_MAC_BYP,
    BM_MAC_BYP_PCS,
    BM_MAC_XAUI_PCS_SEL_ACTIVE,
    BM_MAC_XAUI_PCS_PACE_EN,
    BM_MAC_XAUI_PCS_GENERIC,
    BM_MAC_LAST
} block_mac_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_MAC_H */
