/*


 Copyright (c) 2002-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable format
 (e.g. HEX file) and only in or with products utilizing the Microsemi switch and
 PHY products.  The source code of the software may not be disclosed, transmitted
 or distributed without the prior written permission of Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all ownership,
 copyright, trade secret and proprietary rights in the software and its source code,
 including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL WARRANTIES
 OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES ARE EXPRESS,
 IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION, WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND NON-INFRINGEMENT.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_WIS_H
#define _VTSS_DAYTONA_REG_INIT_WIS_H

// Settings for mode OC192

#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA_OC192                                    VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA(0x1)
#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS_OC192                                     VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA_OC192                                  VTSS_F_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA(0x1)
#define  VTSS_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS_OC192                                VTSS_F_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS(0x1)
#define  VTSS_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2_OC192                                         VTSS_F_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2(0x5)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU_OC192                                     VTSS_F_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA_OC192                                    VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA(0x1)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS_OC192                                     VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE_OC192                                       VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH_OC192                                VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH_OC192                                VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z0_TX_Z0_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_Z0_TX_Z0(0xcc)
#define  VTSS_EWIS_TX_BYTE_TX_E1_TX_E1_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_E1_TX_E1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_F1_TX_F1_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_F1_TX_F1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D1_TX_D1_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_D1_TX_D1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D2_TX_D2_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_D2_TX_D2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D3_TX_D3_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_D3_TX_D3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K1_TX_K1_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_K1_TX_K1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K2_TX_K2_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_K2_TX_K2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D4_TX_D4_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_D4_TX_D4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D5_TX_D5_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_D5_TX_D5(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D6_TX_D6_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_D6_TX_D6(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D7_TX_D7_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_D7_TX_D7(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D8_TX_D8_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_D8_TX_D8(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D9_TX_D9_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_D9_TX_D9(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D10_TX_D10_OC192                                                      VTSS_F_EWIS_TX_BYTE_TX_D10_TX_D10(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D11_TX_D11_OC192                                                      VTSS_F_EWIS_TX_BYTE_TX_D11_TX_D11(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D12_TX_D12_OC192                                                      VTSS_F_EWIS_TX_BYTE_TX_D12_TX_D12(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_S1_TX_S1_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_S1_TX_S1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_E2_TX_E2_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_E2_TX_E2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z1_TX_Z1_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_Z1_TX_Z1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z2_TX_Z2_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_Z2_TX_Z2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_C2_TX_C2_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_C2_TX_C2(0x5)
#define  VTSS_EWIS_TX_BYTE_TX_F2_TX_F2_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_F2_TX_F2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_H4_TX_H4_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_H4_TX_H4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z3_TX_Z3_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_Z3_TX_Z3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z4_TX_Z4_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_Z4_TX_Z4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_N1_TX_N1_OC192                                                        VTSS_F_EWIS_TX_BYTE_TX_N1_TX_N1(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)


// Settings for mode WAN

#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA_WAN                                      VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA(0x1)
#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS_WAN                                       VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA_WAN                                    VTSS_F_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS_WAN                                  VTSS_F_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2_WAN                                           VTSS_F_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2(0x1a)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU_WAN                                       VTSS_F_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA_WAN                                      VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA(0x1)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS_WAN                                       VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE_WAN                                         VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE(0x1)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH_WAN                                  VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH_WAN                                  VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z0_TX_Z0_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_Z0_TX_Z0(0xcc)
#define  VTSS_EWIS_TX_BYTE_TX_E1_TX_E1_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_E1_TX_E1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_F1_TX_F1_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_F1_TX_F1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D1_TX_D1_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_D1_TX_D1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D2_TX_D2_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_D2_TX_D2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D3_TX_D3_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_D3_TX_D3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K1_TX_K1_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_K1_TX_K1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K2_TX_K2_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_K2_TX_K2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D4_TX_D4_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_D4_TX_D4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D5_TX_D5_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_D5_TX_D5(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D6_TX_D6_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_D6_TX_D6(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D7_TX_D7_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_D7_TX_D7(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D8_TX_D8_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_D8_TX_D8(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D9_TX_D9_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_D9_TX_D9(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D10_TX_D10_WAN                                                        VTSS_F_EWIS_TX_BYTE_TX_D10_TX_D10(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D11_TX_D11_WAN                                                        VTSS_F_EWIS_TX_BYTE_TX_D11_TX_D11(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D12_TX_D12_WAN                                                        VTSS_F_EWIS_TX_BYTE_TX_D12_TX_D12(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_S1_TX_S1_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_S1_TX_S1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_E2_TX_E2_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_E2_TX_E2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z1_TX_Z1_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_Z1_TX_Z1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z2_TX_Z2_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_Z2_TX_Z2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_C2_TX_C2_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_C2_TX_C2(0x1a)
#define  VTSS_EWIS_TX_BYTE_TX_F2_TX_F2_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_F2_TX_F2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_H4_TX_H4_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_H4_TX_H4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z3_TX_Z3_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_Z3_TX_Z3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z4_TX_Z4_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_Z4_TX_Z4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_N1_TX_N1_WAN                                                          VTSS_F_EWIS_TX_BYTE_TX_N1_TX_N1(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)


// Settings for mode BYP

#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA_BYP                                      VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS_BYP                                       VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS(0x1)
#define  VTSS_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA_BYP                                    VTSS_F_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS_BYP                                  VTSS_F_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2_BYP                                           VTSS_F_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU_BYP                                       VTSS_F_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA_BYP                                      VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS_BYP                                       VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS(0x1)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE_BYP                                         VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH_BYP                                  VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH_BYP                                  VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z0_TX_Z0_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_Z0_TX_Z0(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_E1_TX_E1_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_E1_TX_E1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_F1_TX_F1_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_F1_TX_F1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D1_TX_D1_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_D1_TX_D1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D2_TX_D2_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_D2_TX_D2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D3_TX_D3_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_D3_TX_D3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K1_TX_K1_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_K1_TX_K1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K2_TX_K2_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_K2_TX_K2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D4_TX_D4_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_D4_TX_D4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D5_TX_D5_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_D5_TX_D5(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D6_TX_D6_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_D6_TX_D6(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D7_TX_D7_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_D7_TX_D7(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D8_TX_D8_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_D8_TX_D8(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D9_TX_D9_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_D9_TX_D9(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D10_TX_D10_BYP                                                        VTSS_F_EWIS_TX_BYTE_TX_D10_TX_D10(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D11_TX_D11_BYP                                                        VTSS_F_EWIS_TX_BYTE_TX_D11_TX_D11(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D12_TX_D12_BYP                                                        VTSS_F_EWIS_TX_BYTE_TX_D12_TX_D12(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_S1_TX_S1_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_S1_TX_S1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_E2_TX_E2_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_E2_TX_E2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z1_TX_Z1_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_Z1_TX_Z1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z2_TX_Z2_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_Z2_TX_Z2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_C2_TX_C2_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_C2_TX_C2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_F2_TX_F2_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_F2_TX_F2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_H4_TX_H4_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_H4_TX_H4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z3_TX_Z3_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_Z3_TX_Z3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z4_TX_Z4_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_Z4_TX_Z4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_N1_TX_N1_BYP                                                          VTSS_F_EWIS_TX_BYTE_TX_N1_TX_N1(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_BYP                                                        VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_BYP                                                        VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x0)


// Settings for mode WAN_P

#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA_WAN_P                                    VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA(0x1)
#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS_WAN_P                                     VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS(0x1)
#define  VTSS_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA_WAN_P                                  VTSS_F_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS_WAN_P                                VTSS_F_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2_WAN_P                                         VTSS_F_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2(0x1a)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU_WAN_P                                     VTSS_F_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA_WAN_P                                    VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS_WAN_P                                     VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS(0x1)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE_WAN_P                                       VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH_WAN_P                                VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH_WAN_P                                VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z0_TX_Z0_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_Z0_TX_Z0(0xcc)
#define  VTSS_EWIS_TX_BYTE_TX_E1_TX_E1_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_E1_TX_E1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_F1_TX_F1_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_F1_TX_F1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D1_TX_D1_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_D1_TX_D1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D2_TX_D2_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_D2_TX_D2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D3_TX_D3_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_D3_TX_D3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K1_TX_K1_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_K1_TX_K1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K2_TX_K2_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_K2_TX_K2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D4_TX_D4_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_D4_TX_D4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D5_TX_D5_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_D5_TX_D5(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D6_TX_D6_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_D6_TX_D6(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D7_TX_D7_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_D7_TX_D7(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D8_TX_D8_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_D8_TX_D8(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D9_TX_D9_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_D9_TX_D9(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D10_TX_D10_WAN_P                                                      VTSS_F_EWIS_TX_BYTE_TX_D10_TX_D10(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D11_TX_D11_WAN_P                                                      VTSS_F_EWIS_TX_BYTE_TX_D11_TX_D11(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D12_TX_D12_WAN_P                                                      VTSS_F_EWIS_TX_BYTE_TX_D12_TX_D12(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_S1_TX_S1_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_S1_TX_S1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_E2_TX_E2_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_E2_TX_E2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z1_TX_Z1_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_Z1_TX_Z1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z2_TX_Z2_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_Z2_TX_Z2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_C2_TX_C2_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_C2_TX_C2(0x1a)
#define  VTSS_EWIS_TX_BYTE_TX_F2_TX_F2_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_F2_TX_F2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_H4_TX_H4_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_H4_TX_H4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z3_TX_Z3_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_Z3_TX_Z3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z4_TX_Z4_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_Z4_TX_Z4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_N1_TX_N1_WAN_P                                                        VTSS_F_EWIS_TX_BYTE_TX_N1_TX_N1(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_WAN_P                                                      VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_WAN_P                                                      VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)


// Settings for mode OC192_M

#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA_OC192_M                                  VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_CLK_ENA(0x1)
#define  VTSS_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS_OC192_M                                   VTSS_F_EWIS_RX_WIS_CTRL_RX_TOP_LEVEL_RX_WIS_BYPASS(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA_OC192_M                                VTSS_F_EWIS_RX_WIS_CTRL_MISC_SOH_CTRL_RX_FRM_SYNC_ENA(0x0)
#define  VTSS_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS_OC192_M                              VTSS_F_EWIS_RX_WIS_CTRL_PNTR_INTRPRTR_CTRL_RX_PI_BYPASS(0x1)
#define  VTSS_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2_OC192_M                                       VTSS_F_EWIS_RX_WIS_CTRL_C2_CTRL_RX_EXPECTED_C2(0x5)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU_OC192_M                                   VTSS_F_EWIS_TX_WIS_CTRL_TX_PASSTHRU_TX_K2_PASSTHRU(0x1)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA_OC192_M                                  VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_CLK_ENA(0x1)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS_OC192_M                                   VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_WIS_BYPASS(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE_OC192_M                                     VTSS_F_EWIS_TX_WIS_CTRL_TX_TOP_LEVEL_TX_MAP_MODE(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH_OC192_M                              VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J0_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH_OC192_M                              VTSS_F_EWIS_TX_WIS_CTRL_TX_MISC_CTRL_TX_J1_TRACE_LENGTH(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z0_TX_Z0_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_Z0_TX_Z0(0xcc)
#define  VTSS_EWIS_TX_BYTE_TX_E1_TX_E1_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_E1_TX_E1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_F1_TX_F1_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_F1_TX_F1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D1_TX_D1_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_D1_TX_D1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D2_TX_D2_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_D2_TX_D2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D3_TX_D3_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_D3_TX_D3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K1_TX_K1_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_K1_TX_K1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_K2_TX_K2_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_K2_TX_K2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D4_TX_D4_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_D4_TX_D4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D5_TX_D5_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_D5_TX_D5(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D6_TX_D6_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_D6_TX_D6(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D7_TX_D7_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_D7_TX_D7(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D8_TX_D8_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_D8_TX_D8(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D9_TX_D9_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_D9_TX_D9(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D10_TX_D10_OC192_M                                                    VTSS_F_EWIS_TX_BYTE_TX_D10_TX_D10(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D11_TX_D11_OC192_M                                                    VTSS_F_EWIS_TX_BYTE_TX_D11_TX_D11(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_D12_TX_D12_OC192_M                                                    VTSS_F_EWIS_TX_BYTE_TX_D12_TX_D12(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_S1_TX_S1_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_S1_TX_S1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_E2_TX_E2_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_E2_TX_E2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z1_TX_Z1_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_Z1_TX_Z1(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z2_TX_Z2_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_Z2_TX_Z2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_C2_TX_C2_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_C2_TX_C2(0x5)
#define  VTSS_EWIS_TX_BYTE_TX_F2_TX_F2_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_F2_TX_F2(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_H4_TX_H4_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_H4_TX_H4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z3_TX_Z3_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_Z3_TX_Z3(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_Z4_TX_Z4_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_Z4_TX_Z4(0x0)
#define  VTSS_EWIS_TX_BYTE_TX_N1_TX_N1_OC192_M                                                      VTSS_F_EWIS_TX_BYTE_TX_N1_TX_N1(0x0)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J0_INS_TX_J0_TX_J0_OC192_M                                                    VTSS_F_EWIS_TX_J0_INS_TX_J0_TX_J0(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)
#define  VTSS_EWIS_TX_J1_INS_TX_J1_TX_J1_OC192_M                                                    VTSS_F_EWIS_TX_J1_INS_TX_J1_TX_J1(0x40)




typedef enum {
    BM_WIS_OC192,
    BM_WIS_WAN,
    BM_WIS_BYP,
    BM_WIS_WAN_P,
    BM_WIS_OC192_M,
    BM_WIS_LAST
} block_wis_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_WIS_H */
