/*


 Copyright (c) 2004-2018 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_UPI_HSS6G_H
#define _VTSS_DAYTONA_REG_INIT_UPI_HSS6G_H

// Settings for mode OTU2_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2_SDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2_SDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2_SDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2_SDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_SDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_SDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2_DDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2_DDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2_DDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2_DDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_DDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_DDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2_SDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2_SDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2_SDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2_SDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_SDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_SDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2_DDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2_DDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2_DDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2_DDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_DDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_DDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2E_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2E_SDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2E_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2E_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2E_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2E_DDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2E_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2E_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2E_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2E_SDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2E_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2E_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2E_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2E_DDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2E_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2E_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU1E_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU1E_SDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU1E_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU1E_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU1E_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU1E_DDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU1E_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU1E_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU1E_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU1E_SDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU1E_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU1E_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU1E_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU1E_DDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU1E_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU1E_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2F_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2F_SDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2F_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2F_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2F_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2F_DDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2F_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2F_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2F_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2F_SDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2F_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2F_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2F_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2F_DDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2F_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2F_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode TFI5_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_TFI5_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_TFI5_SDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_TFI5_SDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_TFI5_SDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_TFI5_SDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_TFI5_SDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_TFI5_SDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode TFI5_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_TFI5_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_TFI5_DDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x3)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_TFI5_DDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_TFI5_DDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_TFI5_DDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_TFI5_DDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_TFI5_DDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode TFI5_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_TFI5_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_TFI5_SDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_TFI5_SDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_TFI5_SDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_TFI5_SDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_TFI5_SDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_TFI5_SDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode TFI5_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_TFI5_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_TFI5_DDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x3)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_TFI5_DDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_TFI5_DDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_TFI5_DDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_TFI5_DDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_TFI5_DDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode XAUI_10GE_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_XAUI_10GE_SDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_XAUI_10GE_SDR                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_XAUI_10GE_SDR                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_XAUI_10GE_SDR                    VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_XAUI_10GE_SDR                    VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_XAUI_10GE_SDR                    VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_XAUI_10GE_SDR                    VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode XAUI_10GE_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_XAUI_10GE_DDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_XAUI_10GE_DDR                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_XAUI_10GE_DDR                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_XAUI_10GE_DDR                    VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_XAUI_10GE_DDR                    VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_XAUI_10GE_DDR                    VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_XAUI_10GE_DDR                    VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode XAUI_10GFC_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_XAUI_10GFC_SDR                VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_XAUI_10GFC_SDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_XAUI_10GFC_SDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_XAUI_10GFC_SDR                   VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_XAUI_10GFC_SDR                   VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_XAUI_10GFC_SDR                   VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_XAUI_10GFC_SDR                   VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode XAUI_10GFC_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_XAUI_10GFC_DDR                VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_XAUI_10GFC_DDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x3)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_XAUI_10GFC_DDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_XAUI_10GFC_DDR                   VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_XAUI_10GFC_DDR                   VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_XAUI_10GFC_DDR                   VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_XAUI_10GFC_DDR                   VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode UNUSED

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_UNUSED                        VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_UNUSED                         VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_UNUSED                         VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_UNUSED                           VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_UNUSED                           VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_UNUSED                           VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_UNUSED                           VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)




typedef enum {
    BM_UPI_HSS6G_OTU2_SDR,
    BM_UPI_HSS6G_OTU2_DDR,
    BM_UPI_HSS6G_OTU2_SDR_X4,
    BM_UPI_HSS6G_OTU2_DDR_X4,
    BM_UPI_HSS6G_OTU2E_SDR,
    BM_UPI_HSS6G_OTU2E_DDR,
    BM_UPI_HSS6G_OTU2E_SDR_X4,
    BM_UPI_HSS6G_OTU2E_DDR_X4,
    BM_UPI_HSS6G_OTU1E_SDR,
    BM_UPI_HSS6G_OTU1E_DDR,
    BM_UPI_HSS6G_OTU1E_SDR_X4,
    BM_UPI_HSS6G_OTU1E_DDR_X4,
    BM_UPI_HSS6G_OTU2F_SDR,
    BM_UPI_HSS6G_OTU2F_DDR,
    BM_UPI_HSS6G_OTU2F_SDR_X4,
    BM_UPI_HSS6G_OTU2F_DDR_X4,
    BM_UPI_HSS6G_TFI5_SDR,
    BM_UPI_HSS6G_TFI5_DDR,
    BM_UPI_HSS6G_TFI5_SDR_X4,
    BM_UPI_HSS6G_TFI5_DDR_X4,
    BM_UPI_HSS6G_XAUI_10GE_SDR,
    BM_UPI_HSS6G_XAUI_10GE_DDR,
    BM_UPI_HSS6G_XAUI_10GFC_SDR,
    BM_UPI_HSS6G_XAUI_10GFC_DDR,
    BM_UPI_HSS6G_UNUSED,
    BM_UPI_HSS6G_LAST
} block_upi_hss6g_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_UPI_HSS6G_H */
