/*


 Copyright (c) 2004-2018 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_PCS_H
#define _VTSS_DAYTONA_REG_INIT_PCS_H

// Settings for mode INTR_MON

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_INTR_MON                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_INTR_MON                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_INTR_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_INTR_MON                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_INTR_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_INTR_MON                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_INTR_MON                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_INTR_MON                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_INTR_MON                             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_INTR_MON                                  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_INTR_MON                             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_INTR_MON                             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_INTR_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_INTR_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_INTR_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0xc)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_INTR_MON                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0x20)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_INTR_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0xdc)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_INTR_MON                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0xf2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_INTR_MON                              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x25d8)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_INTR_MON                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_INTR_MON                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)


// Settings for mode INTR_MON_LOS

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_INTR_MON_LOS                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_INTR_MON_LOS                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_INTR_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_INTR_MON_LOS                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_INTR_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_INTR_MON_LOS                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_INTR_MON_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_INTR_MON_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_INTR_MON_LOS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_INTR_MON_LOS                              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_INTR_MON_LOS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_INTR_MON_LOS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_INTR_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_INTR_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_INTR_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0xc)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_INTR_MON_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0x20)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_INTR_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0xdc)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_INTR_MON_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0xf2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_INTR_MON_LOS                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x25d8)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_INTR_MON_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_INTR_MON_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)


// Settings for mode PASS_MON

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_PASS_MON                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_PASS_MON                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_PASS_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_PASS_MON                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_PASS_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_PASS_MON                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_PASS_MON                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_PASS_MON                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_PASS_MON                             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_PASS_MON                                  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_PASS_MON                             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_PASS_MON                             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_PASS_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_PASS_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_PASS_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_PASS_MON                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_PASS_MON                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0x40)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_PASS_MON                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0xc0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_PASS_MON                              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x28c6)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_PASS_MON                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_PASS_MON                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)


// Settings for mode PASS_MON_WIS

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_PASS_MON_WIS                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_PASS_MON_WIS                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_PASS_MON_WIS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_PASS_MON_WIS                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_PASS_MON_WIS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_PASS_MON_WIS                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_PASS_MON_WIS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_PASS_MON_WIS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_PASS_MON_WIS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_PASS_MON_WIS                              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_PASS_MON_WIS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_PASS_MON_WIS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_PASS_MON_WIS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_PASS_MON_WIS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_PASS_MON_WIS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_PASS_MON_WIS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_PASS_MON_WIS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0xdc)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_PASS_MON_WIS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0xf2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_PASS_MON_WIS                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x28c6)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_PASS_MON_WIS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_PASS_MON_WIS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)


// Settings for mode PASS_MON_LOS

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_PASS_MON_LOS                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_PASS_MON_LOS                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_PASS_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_PASS_MON_LOS                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_PASS_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_PASS_MON_LOS                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_PASS_MON_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_PASS_MON_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_PASS_MON_LOS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_PASS_MON_LOS                              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_PASS_MON_LOS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_PASS_MON_LOS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_PASS_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_PASS_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_PASS_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_PASS_MON_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_PASS_MON_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0x40)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_PASS_MON_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0xc0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_PASS_MON_LOS                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x28c6)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_PASS_MON_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_PASS_MON_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)


// Settings for mode BYP

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_BYP                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_BYP                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_BYP                                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_BYP                              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_BYP                                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_BYP                              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_BYP                                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_BYP                                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_BYP                                  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_BYP                                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_BYP                                  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_BYP                                  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_BYP                                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_BYP                                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_BYP                                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_BYP                               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_BYP                                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_BYP                               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_BYP                                   VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_BYP                                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_BYP                                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)


// Settings for mode MIN_IFG_1

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_MIN_IFG_1                    VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_MIN_IFG_1                    VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_MIN_IFG_1                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_MIN_IFG_1                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_MIN_IFG_1                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_MIN_IFG_1                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_MIN_IFG_1                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_MIN_IFG_1                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_MIN_IFG_1                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_MIN_IFG_1                                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_MIN_IFG_1                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_MIN_IFG_1                            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_MIN_IFG_1                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_MIN_IFG_1                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_MIN_IFG_1                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0xc)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_MIN_IFG_1                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0x20)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_MIN_IFG_1                          VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0xdc)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_MIN_IFG_1                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0xf2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_MIN_IFG_1                             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x25d8)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_MIN_IFG_1                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_MIN_IFG_1                           VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)


// Settings for mode MIN_IFG_1_LOS

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_MIN_IFG_1_LOS                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_MIN_IFG_1_LOS                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_MIN_IFG_1_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_MIN_IFG_1_LOS                    VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_MIN_IFG_1_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_MIN_IFG_1_LOS                    VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_MIN_IFG_1_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_MIN_IFG_1_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_MIN_IFG_1_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_MIN_IFG_1_LOS                             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_MIN_IFG_1_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_MIN_IFG_1_LOS                        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_MIN_IFG_1_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_MIN_IFG_1_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_MIN_IFG_1_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0xc)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_MIN_IFG_1_LOS                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0x20)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_MIN_IFG_1_LOS                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0xdc)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_MIN_IFG_1_LOS                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0xf2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_MIN_IFG_1_LOS                         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x25d8)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_MIN_IFG_1_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_MIN_IFG_1_LOS                       VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)


// Settings for mode INTR_MON_NEW_RATE_DIS

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_INTR_MON_NEW_RATE_DIS        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_INTR_MON_NEW_RATE_DIS        VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_INTR_MON_NEW_RATE_DIS              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_INTR_MON_NEW_RATE_DIS            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_INTR_MON_NEW_RATE_DIS              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_INTR_MON_NEW_RATE_DIS            VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_INTR_MON_NEW_RATE_DIS               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_INTR_MON_NEW_RATE_DIS               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_INTR_MON_NEW_RATE_DIS                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_INTR_MON_NEW_RATE_DIS                     VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_INTR_MON_NEW_RATE_DIS                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_INTR_MON_NEW_RATE_DIS                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_INTR_MON_NEW_RATE_DIS              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_INTR_MON_NEW_RATE_DIS              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x2)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_INTR_MON_NEW_RATE_DIS              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0x6)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_INTR_MON_NEW_RATE_DIS             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0xa)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_INTR_MON_NEW_RATE_DIS              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0x6)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_INTR_MON_NEW_RATE_DIS             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0xa)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_INTR_MON_NEW_RATE_DIS                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x25d8)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_INTR_MON_NEW_RATE_DIS               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_INTR_MON_NEW_RATE_DIS               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)


// Settings for mode INTR_MON_NEW_RATE_EN

#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE_INTR_MON_NEW_RATE_EN         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE_INTR_MON_NEW_RATE_EN         VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_RADAPT_ENABLE(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA_INTR_MON_NEW_RATE_EN               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA_INTR_MON_NEW_RATE_EN             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA_INTR_MON_NEW_RATE_EN               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PMA_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA_INTR_MON_NEW_RATE_EN             VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_XGMII_CLK_ENA(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS_INTR_MON_NEW_RATE_EN                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS_INTR_MON_NEW_RATE_EN                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_PCS_BYPASS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON_INTR_MON_NEW_RATE_EN                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_INPUT_MON(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS_INTR_MON_NEW_RATE_EN                      VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_USE_LOS(0x0)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP_INTR_MON_NEW_RATE_EN                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP_INTR_MON_NEW_RATE_EN                 VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG_INTR_MON_NEW_RATE_EN               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_MIN_IFG(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG_INTR_MON_NEW_RATE_EN               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_MIN_IFG(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL_INTR_MON_NEW_RATE_EN               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_ADD_LVL(0x6)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL_INTR_MON_NEW_RATE_EN              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_FIFO_CFG_TX_DROP_LVL(0xa)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL_INTR_MON_NEW_RATE_EN               VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_ADD_LVL(0x6)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL_INTR_MON_NEW_RATE_EN              VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_FIFO_CFG_RX_DROP_LVL(0xa)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125_INTR_MON_NEW_RATE_EN                  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(0x25d8)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH_INTR_MON_NEW_RATE_EN                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_FIFO_FLUSH(0x1)
#define  VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH_INTR_MON_NEW_RATE_EN                VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_FIFO_FLUSH(0x1)




typedef enum {
    BM_PCS_INTR_MON,
    BM_PCS_INTR_MON_LOS,
    BM_PCS_PASS_MON,
    BM_PCS_PASS_MON_WIS,
    BM_PCS_PASS_MON_LOS,
    BM_PCS_BYP,
    BM_PCS_MIN_IFG_1,
    BM_PCS_MIN_IFG_1_LOS,
    BM_PCS_INTR_MON_NEW_RATE_DIS,
    BM_PCS_INTR_MON_NEW_RATE_EN,
    BM_PCS_LAST
} block_pcs_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_PCS_H */
