/*


 Copyright (c) 2002-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable format
 (e.g. HEX file) and only in or with products utilizing the Microsemi switch and
 PHY products.  The source code of the software may not be disclosed, transmitted
 or distributed without the prior written permission of Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all ownership,
 copyright, trade secret and proprietary rights in the software and its source code,
 including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL WARRANTIES
 OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES ARE EXPRESS,
 IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION, WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND NON-INFRINGEMENT.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_UPI_HSS6G_H
#define _VTSS_DAYTONA_REG_INIT_UPI_HSS6G_H

// Settings for mode OTU2_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2_SDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2_SDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2_SDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2_SDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_SDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_SDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2_DDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2_DDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2_DDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2_DDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_DDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_DDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2_SDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2_SDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2_SDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2_SDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_SDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_SDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2_DDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2_DDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2_DDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2_DDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2_DDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2_DDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2E_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2E_SDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2E_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2E_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2E_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2E_DDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2E_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2E_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2E_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2E_SDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2E_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2E_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2E_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2E_DDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2E_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2E_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2E_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2E_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2E_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2E_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU1E_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU1E_SDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU1E_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU1E_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU1E_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU1E_DDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU1E_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU1E_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU1E_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU1E_SDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU1E_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU1E_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU1E_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU1E_DDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU1E_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU1E_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU1E_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU1E_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU1E_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU1E_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2F_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2F_SDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2F_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2F_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F_SDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_SDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2F_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2F_DDR                     VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2F_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2F_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F_DDR                        VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_DDR                        VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode OTU2F_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2F_SDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2F_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2F_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F_SDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_SDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode OTU2F_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_OTU2F_DDR_X4                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_OTU2F_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_OTU2F_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_OTU2F_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_OTU2F_DDR_X4                     VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_OTU2F_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_OTU2F_DDR_X4                     VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode TFI5_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_TFI5_SDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_TFI5_SDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_TFI5_SDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_TFI5_SDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_TFI5_SDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_TFI5_SDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_TFI5_SDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode TFI5_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_TFI5_DDR                      VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_TFI5_DDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x3)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_TFI5_DDR                       VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_TFI5_DDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_TFI5_DDR                         VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_TFI5_DDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_TFI5_DDR                         VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode TFI5_SDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_TFI5_SDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_TFI5_SDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_TFI5_SDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_TFI5_SDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_TFI5_SDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_TFI5_SDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_TFI5_SDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode TFI5_DDR_X4

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_TFI5_DDR_X4                   VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_TFI5_DDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x3)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_TFI5_DDR_X4                    VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_TFI5_DDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_TFI5_DDR_X4                      VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_TFI5_DDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x2)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_TFI5_DDR_X4                      VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode XAUI_10GE_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_XAUI_10GE_SDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_XAUI_10GE_SDR                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_XAUI_10GE_SDR                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_XAUI_10GE_SDR                    VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_XAUI_10GE_SDR                    VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_XAUI_10GE_SDR                    VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_XAUI_10GE_SDR                    VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode XAUI_10GE_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_XAUI_10GE_DDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_XAUI_10GE_DDR                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_XAUI_10GE_DDR                  VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_XAUI_10GE_DDR                    VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_XAUI_10GE_DDR                    VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_XAUI_10GE_DDR                    VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_XAUI_10GE_DDR                    VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode XAUI_10GFC_SDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_XAUI_10GFC_SDR                VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_XAUI_10GFC_SDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_XAUI_10GFC_SDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_XAUI_10GFC_SDR                   VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_XAUI_10GFC_SDR                   VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_XAUI_10GFC_SDR                   VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_XAUI_10GFC_SDR                   VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)


// Settings for mode XAUI_10GFC_DDR

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_XAUI_10GFC_DDR                VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_XAUI_10GFC_DDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x3)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_XAUI_10GFC_DDR                 VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_XAUI_10GFC_DDR                   VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_XAUI_10GFC_DDR                   VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x0)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_XAUI_10GFC_DDR                   VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x3)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_XAUI_10GFC_DDR                   VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x0)


// Settings for mode UNUSED

#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL_UNUSED                        VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_PWDNPLL(0x1)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL_UNUSED                         VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_DIVSEL(0x0)
#define  VTSS_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE_UNUSED                         VTSS_F_UPI_UPI_HSS6G_PLL_RST_CONFIG_STAT_UPI_HSS6G_PLL_ACMODE(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL_UNUSED                           VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL_UNUSED                           VTSS_F_UPI_HSS6G_TX_HSS6G_TRANSMIT_CONFIGURATION_MODE_RTSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL_UNUSED                           VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_BWSEL(0x1)
#define  VTSS_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL_UNUSED                           VTSS_F_UPI_HSS6G_RX_HSS6G_RECEIVER_CONFIGURATION_MODE_RTSEL(0x1)




typedef enum {
    BM_UPI_HSS6G_OTU2_SDR,
    BM_UPI_HSS6G_OTU2_DDR,
    BM_UPI_HSS6G_OTU2_SDR_X4,
    BM_UPI_HSS6G_OTU2_DDR_X4,
    BM_UPI_HSS6G_OTU2E_SDR,
    BM_UPI_HSS6G_OTU2E_DDR,
    BM_UPI_HSS6G_OTU2E_SDR_X4,
    BM_UPI_HSS6G_OTU2E_DDR_X4,
    BM_UPI_HSS6G_OTU1E_SDR,
    BM_UPI_HSS6G_OTU1E_DDR,
    BM_UPI_HSS6G_OTU1E_SDR_X4,
    BM_UPI_HSS6G_OTU1E_DDR_X4,
    BM_UPI_HSS6G_OTU2F_SDR,
    BM_UPI_HSS6G_OTU2F_DDR,
    BM_UPI_HSS6G_OTU2F_SDR_X4,
    BM_UPI_HSS6G_OTU2F_DDR_X4,
    BM_UPI_HSS6G_TFI5_SDR,
    BM_UPI_HSS6G_TFI5_DDR,
    BM_UPI_HSS6G_TFI5_SDR_X4,
    BM_UPI_HSS6G_TFI5_DDR_X4,
    BM_UPI_HSS6G_XAUI_10GE_SDR,
    BM_UPI_HSS6G_XAUI_10GE_DDR,
    BM_UPI_HSS6G_XAUI_10GFC_SDR,
    BM_UPI_HSS6G_XAUI_10GFC_DDR,
    BM_UPI_HSS6G_UNUSED,
    BM_UPI_HSS6G_LAST
} block_upi_hss6g_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_UPI_HSS6G_H */
