/*


 Copyright (c) 2002-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable format
 (e.g. HEX file) and only in or with products utilizing the Microsemi switch and
 PHY products.  The source code of the software may not be disclosed, transmitted
 or distributed without the prior written permission of Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all ownership,
 copyright, trade secret and proprietary rights in the software and its source code,
 including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL WARRANTIES
 OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES ARE EXPRESS,
 IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION, WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND NON-INFRINGEMENT.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_OTU_FEC_H
#define _VTSS_DAYTONA_REG_INIT_OTU_FEC_H

// Settings for mode EFECI7

#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING_EFECI7                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_EFECI7                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE_EFECI7                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_EFECI7                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL_EFECI7                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL(0x1)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY_EFECI7           VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS_EFECI7         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN_EFECI7         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS_EFECI7     VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN_EFECI7          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA_EFECI7            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST_EFECI7            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS_EFECI7            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA_EFECI7            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA(0x0)


// Settings for mode EFECI4

#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING_EFECI4                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_EFECI4                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE_EFECI4                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_EFECI4                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x1)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL_EFECI4                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY_EFECI4           VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY(0x3)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS_EFECI4         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN_EFECI4         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS_EFECI4     VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN_EFECI4          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN(0x1)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA_EFECI4            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA(0x1)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST_EFECI4            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS_EFECI4            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA_EFECI4            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA(0x1)


// Settings for mode RSFEC

#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING_RSFEC                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_RSFEC                 VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE_RSFEC                   VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_RSFEC                 VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL_RSFEC                                   VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY_RSFEC            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS_RSFEC          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN_RSFEC          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS_RSFEC      VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN_RSFEC           VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA_RSFEC             VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST_RSFEC             VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS_RSFEC             VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS(0x1)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA_RSFEC             VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA(0x0)


// Settings for mode UNUSED

#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING_UNUSED                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_FEC_BLANKING(0x1)
#define  VTSS_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_UNUSED                VTSS_F_OTN_WRAPPER_XCO2_TX_OTN_XCO2_TX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE_UNUSED                  VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_FEC_ENABLE(0x0)
#define  VTSS_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC_UNUSED                VTSS_F_OTN_WRAPPER_XCO2_RX_OTN_XCO2_RX_OTN_GLOBAL_CONTROL_EXTERNAL_FEC(0x0)
#define  VTSS_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL_UNUSED                                  VTSS_F_OTN_WRAPPER_WRAPPER_GROUP_CONTROL_REG_FEC_SEL(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY_UNUSED           VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LATENCY(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS_UNUSED         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_DI_BYPASS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN_UNUSED         VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_PMTICK_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS_UNUSED     VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_LOAD_COUNTERS(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN_UNUSED          VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SCRAM_EN(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA_UNUSED            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_ENA(0x0)
#define  VTSS_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST_UNUSED            VTSS_F_EFECI4_EFECI4_DECODER_CFG_EFECI4_DECODER_CONFIG1_CFG_DECODER_SW_RST(0x0)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS_UNUSED            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_BYPASS(0x1)
#define  VTSS_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA_UNUSED            VTSS_F_EFECI4_EFECI4_ENCODER_CFG_EFECI4_ENCODER_CONFIG1_CFG_ENCODER_SW_ENA(0x0)




typedef enum {
    BM_OTU_FEC_EFECI7,
    BM_OTU_FEC_EFECI4,
    BM_OTU_FEC_RSFEC,
    BM_OTU_FEC_UNUSED,
    BM_OTU_FEC_LAST
} block_otu_fec_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_OTU_FEC_H */
